#!/usr/bin/env perl
# -*- Mode: CPerl;
# cperl-indent-level: 4;
# cperl-continued-statement-offset: 4;
# cperl-indent-parens-as-block: t;
# cperl-tabs-always-indent: t;
# cperl-indent-subs-specially: nil;
# -*-
# vim:ts=4:sw=4:expandtab

# To make development easier.
use lib qw(lib);

use Kanla::Plugin;
use Kanla::Plugin::Banner;

sub run {
    signal_error(
        'critical',
'Hello, this is the "fail" plugin. If you read this message, your setup seems to be working :-).',
        [ 'fail', $$ ],
    );
}
